# Generated by Django 3.0.5 on 2022-12-06 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0002_auto_20221206_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applyDate', models.DateField()),
                ('natureOfLeave', models.CharField(max_length=100)),
                ('firstDay', models.DateField()),
                ('lastDay', models.DateField()),
                ('numberOfDays', models.PositiveIntegerField()),
                ('status', models.CharField(default='pending', max_length=100)),
                ('employeeName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
